# exceptions.py
class ApiException(Exception):
    pass